### ISSUE TITLE
spacing should use rem

### ISSUE THREAD

**Issue by shrugs** [urbit/indigo#31]
https://github.com/urbit/indigo/blob/fix%2Fspacing/indigo/css/src/lib/_spacing.scss#L1

afaik best practices are to use rem with an estimated conversion of 16px/rem to create the most flexible spacing measurement. additionally, since we use `rem` values across the project, we should use them here to be consistent.

**Comment by jyng** [comment]
The decision on rem vs px revolves on browser resizing (specifically font-size), so we use `rem` for font-sizing to scale with the user's preferences. But with spacing, I get the sense that the layout quickly loses structure with rem due to scaling. 

The benefits rem buys around updating the root and having it update downstream never seems to be effective — I always end up having to edit the `rem` sizing anyway to maintain the baseline grid.

**Comment by shrugs** [comment]
cool, will defer to y'all on that 👍
